version: '3.8'

services:
  neural-api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: neural-api-dev
    ports:
      - "8080:5000"
    volumes:
      # Mount FastAPI source code for hot reloading
      - .:/app:ro
      - ./app/models/weights:/weights
      # Mount for temporary files (persistent across container restarts)
      - neural_api_temp:/tmp/temp_images
    environment:
      - PYTHONPATH=/app
      - TEMP_IMAGES_DIR=/tmp/temp_images
    env_file:
      - .env
    networks:
      - neural_network
    restart: unless-stopped

    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload

networks:
  neural_network:
    driver: bridge

volumes:
  neural_api_temp:
    driver: local