version: '3.8'

services:
  neural-api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: neural-api-dev
    ports:
      - "8080:5000"
    volumes:
      # Mount source code for hot reloading
      - ./api:/app/api:ro
      - ./models/weights:/app/weights:ro
      # - ./run_test.py:/app/run_test.py
      - ./.env:/app/.env:ro
      # Mount for temporary files (persistent across container restarts)
      - neural_api_temp:/app/api/src/temp_images
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    env_file:
      - .env
    networks:
      - neural_network
    restart: unless-stopped

networks:
  neural_network:
    driver: bridge

volumes:
  neural_api_temp:
    driver: local
